### ISSUE TITLE
RRHH > Vista de aumentos

### ISSUE THREAD

**Issue by tatogranda** [federicobouzas/secdes#32]
- [x] Crear  una solapa en el menú de RRHH donde únicamente se listen los aumentos existentes.
Los mismos deberán poder ser filtrados por todos sus campos

- [x] Validar con usuarios RRHH. Testear.

**Comment by nicpas83** [comment]
Listo.  Pero faltaría que pueda filtrar por DNI.  //  revisar - entender relación de modelo Aumento->Contrato->usuario.

**Comment by nicpas83** [comment]
- [ ] validar con RRHH
